version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000

  db:
    image: mysql:8.0.30-debian
    platform: linux/x86_64
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
