services:
  app:
    build: .
    depends_on:
      - db
      - rabbitmq
    ports:
      - 3000:3000

  db:
    image: mysql:8.0.30-debian
    platform: linux/x86_64
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  mysql-data:
